<?php
/**
 * @file
 * Code for the eoss_webforms feature.
 */

include_once 'eoss_webforms.features.inc';

/**
 * Port over the nid mappings right after the feature has been enabled
 *
 * Implements hook_post_features_enable_feature().
 */
function eoss_webforms_post_features_enable_feature($component) {

  $table = 'migrate_map_custom_nids';
  $class = 'MigrateWebformSubmissionEOSS';
  
  $src_query = Database::getConnection('default', 'eossMigrate')
    ->select('node', 'n1')
    ->fields('n1', array('nid', 'uuid'))
    ->condition('n1.type', 'webform')
    ->orderBy('n1.nid');
  $results_src = $src_query->execute()->fetchAllKeyed();

  foreach ($results_src as $src_nid=>$src_uuid) {
    $query = Database::getConnection('default')
      ->select('node', 'n2')
      ->fields('n2', array('nid', 'title', 'uuid'))
      ->condition('n2.type', 'webform')
      ->condition('n2.uuid', $src_uuid)
      ->orderBy('n2.nid');
    $result = $query->execute()->fetchAll(); // only one UUID
    $result[0]->src_nid = $src_nid;
    $results[$src_uuid] = $result;
  }

  foreach($results as $key => $resultObj) {
    db_insert($table)->fields(array(
      'nid' => $resultObj[0]->nid,
      'title' => $resultObj[0]->title,
      'uuid' => $resultObj[0]->uuid,
      'migration_class' => $class,
      'created' => REQUEST_TIME,
      'src_nid' => $resultObj[0]->src_nid,
    ))->execute();
  }
}
