<?php
/**
 * Code for the Webspark Extras feature.
 */
include_once 'webspark_extras.features.inc';

/**
 * Implements hook_boot()
 *
 * Ensures that all pages are forced to HTTPS if site is on Pantheon
 */
function webspark_extras_boot() {
  global $install_state;
  if (!$install_state) {
    if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) {
      if (!isset($_SERVER['HTTP_X_SSL']) || $_SERVER['HTTP_X_SSL'] != 'ON') {
        header('HTTP/1.0 301 Moved Permanently');
        header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
        // WEBSPARK-813 - friendlier cache-control settings for 301 redirects
        header('Cache-Control: public, max-age=3600');
        exit();
      }
    }
  }
}

/*

function features_help($path, $arg) {
  switch ($path) {
    case 'admin/help#features':
      $output = file_get_contents(drupal_get_path('module', 'features') . '/README.txt');
      return module_exists('markdown') ? filter_xss_admin(module_invoke('markdown', 'filter', 'process', 0, -1, $output)) : '<pre>' . check_plain($output) . '</pre>';
    case 'admin/build/features':
      return '<p>' . t('A "Feature" is a certain type of Drupal module which contains a package of configuration that, when enabled, provides a new set of functionality for your Drupal site. Enable features by selecting the checkboxes below and clicking the Save configuration button. If the configuration of the feature has been changed its "State" will be either "overridden" or "needs review", otherwise it will be "default", indicating that the configuration has not been changed. Click on the state to see more details about the feature and its components.') . '</p>';
  }
}

function webform_help($section = 'admin/help#webform', $arg = NULL) {
  $output = '';
  switch ($section) {
    case 'admin/config/content/webform':
      module_load_include('inc', 'webform', 'includes/webform.admin');
      $type_list = webform_admin_type_list();
      $output = t('Webform enables nodes to have attached forms and questionnaires.');
      if ($type_list) {
        $output .= ' ' . t('To add one, create a !types piece of content.', array('!types' => $type_list));
      }
      else {
        $output .= ' <strong>' . t('Webform is currently not enabled on any content types.') . '</strong> ' . t('To use Webform, please enable it on at least one <a href="!url">content type</a>.', array('!url' => url('admin/structure/types')));
      }
      $output = '<p>' . $output . '</p>';
      break;

    case 'admin/content/webform':
      $output = '<p>' . t('This page lists all of the content on the site that may have a webform attached to it.') . '</p>';
      break;

    case 'admin/help#webform':
      module_load_include('inc', 'webform', 'includes/webform.admin');
      $types = webform_admin_type_list();
      if (empty($types)) {
        $types = t('Webform-enabled piece of content');
        $types_message = t('Webform is currently not enabled on any content types.') . ' ' . t('Visit the <a href="!url">Webform settings</a> page and enable Webform on at least one content type.', array('!url' => url('admin/config/content/webform')));
      }
      else {
        $types_message = t('Optional: Enable Webform on multiple types by visiting the <a href="!url">Webform settings</a> page.', array('!url' => url('admin/config/content/webform')));
      }
      $output = t("<p>This module lets you create forms or questionnaires and define their content. Submissions from these forms are stored in the database and optionally also sent by e-mail to a predefined address.</p>
      <p>Here is how to create one:</p>
      <ul>
        <li>!webform-types-message</li>
        <li>Go to <a href=\"!create-content\">Create content</a> and add a !types piece of content.</li>
        <li>After saving the new content, you will be redirected to the main field list of the form that will be created. Add the fields you would like on your form.</li>
        <li>Once finished adding fields, you may want to send e-mails to administrators or back to the user who filled out the form. Click on the <em>Emails</em> sub-tab underneath the <em>Webform</em> tab on the piece of content.</li>
        <li>Finally, visit the <em>Form settings</em> sub-tab under the <em>Webform</em> tab to configure remaining configurations options for your form.
          <ul>
          <li>Add a confirmation message and/or redirect URL that is to be displayed after successful submission.</li>
          <li>Set a submission limit.</li>
          <li>Determine which roles may submit the form.</li>
          <li>Advanced configuration options such as allowing drafts or show users a message indicating how they can edit their submissions.</li>
          </ul>
        </li>
        <li>Your form is now ready for viewing. After receiving submissions, you can check the results users have submitted by visiting the <em>Results</em> tab on the piece of content.</li>
      </ul>
      <p>Help on adding and configuring the components will be shown after you add your first component.</p>
      ", array(
          '!webform-types-message' => $types_message,
          '!create-content' => url('node/add'),
          '!types' => $types,
        )
      );
      break;

    case 'node/%/webform/conditionals':
      $output .= '<p>' . t('Conditionals may be used to hide or show certain components (or entire pages!) based on the value of other components.') . '</p>';
      break;

    case 'node/%/submission/%/resend':
      $output .= '<p>' . t('This form may be used to resend e-mails configured for this webform. Check the e-mails that need to be sent and click <em>Resend e-mails</em> to send these e-mails again.') . '</p>';
      break;
  }

  return $output;
}
*/


/**
 * Implements hook_help().
 */
function webspark_extras_help($section, $arg = NULL) {
  $output = '';
  switch ($section) {
    case 'admin/reports/asu-rfi-submissions-report':
      $output = "<h2>This will be the RFI sub report view's help text - is this in a block??</h2>";
      break;
    case 'admin/help#webspark-extras':
      $output = "<p>admin/help#webspark-extras text.</p>";
      break;
  }
  return $output;
}

/**
 * Implements hook_page_alter()
 */
function webspark_extras_page_alter(&$page) {
  $page['header']['skip_html'] = array(
    '#weight' => -100,
    '#markup' => '<div class="accessibility-hide"><a href="#main-wrapper" id="skip_to_content">Skip to Main Page Content</a></div>',
  );
  $page['header']['#sorted'] = FALSE;
}

/**
 * Implements hook_quicktabs_tabstyles()
 */
function webspark_extras_quicktabs_tabstyles() {
  $tabstyles_directory = drupal_get_path('module', 'webspark_extras') . '/tabstyles';
  return array($tabstyles_directory . '/asu_web_standards/asu_web_standards.css' => t('ASU Web Standards'));
}

/**
 * Implementation of hook_entity_info_alter()
 */
function webspark_extras_entity_info_alter(&$entity_info) {
  /* WEBSPARK-1123 - Obscuring Panopoly Widgets-generated spotlight in IPE UI */
  $entity_info['fieldable_panels_pane']['bundles']['map']['pane category'] = t('ASU Deprecated');
  $entity_info['fieldable_panels_pane']['bundles']['map']['pane icon'] = drupal_get_path('module', 'webspark_panels_styles') . '/images/icon_map_DEP.png';
  $entity_info['fieldable_panels_pane']['bundles']['map']['pane top level'] = FALSE;
  $entity_info['fieldable_panels_pane']['bundles']['spotlight']['pane category'] = t('ASU Deprecated');
  $entity_info['fieldable_panels_pane']['bundles']['spotlight']['pane icon'] = drupal_get_path('module', 'webspark_panels_styles') . '/images/icon_spotlight_DEP.png';
  $entity_info['fieldable_panels_pane']['bundles']['spotlight']['pane top level'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function webspark_extras_form_update_manager_update_form_alter(&$form, &$form_state, $form_id) {

  if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) {

    $summary = "<p>Only apply updates to projects (modules/themes) <strong>explicitly listed in Webspark</strong> as needing to be updated
    - regardless of what projects the Pantheon Dashboard is listing as projects to update under 'Status -> Extensions'.</p>";

    $long_message = "
  <p><strong>Q</strong>: Why is Pantheon's Dashboard telling me to update modules or themes, but they aren't listed here?</p>
  <p><img src='/" . drupal_get_path('module', 'webspark_extras') . "/images/Pantheon-dashboard-project-status.jpg'
  style='float: right; margin: 0 0 0 1em;' title='Pantheon Dashboard with update list' alt='Pantheon Dashboard with update list' />
  <strong>A:</strong> Webspark has many projects (modules/themes) installed in the /profiles/openasu directory that only Webspark
  maintainers are supposed to update. Those projects' update statuses have been intentionally filtered out of update lists in
  Webspark users don't errantly assume that they need to update them.</p>
  <p>Pantheon's dashboard, however, is showing an unfiltered list of every included project under Status -> Extensions
  regardless of where they're installed (see attached image).</p>
  <p>As a result, some Webspark users have dutifully but errantly updated those projects outside of the normal Webspark
  update workflow - and created problems that later popped up the next time Webspark updates had to be applied to
  those same projects.</p>
  <p><strong>Q:</strong> What projects am I responsible for updating?</p>
  <p><strong>A:</strong> Only projects that have been added to the site and aren't part of Webspark out-of-the-box
  (If they were installed correctly, they'll be somewhere in the /sites directory).</p>
  <p><strong>Q:</strong> What if I still want to override the Webspark-maintained version of a project (with a newer, patched, or otherwise different version)?</p>
  <p><strong>A:</strong> This can be done by adding the custom version of the project in its appropriate /sites/all directory
  (modules/themes/libraries), and then rebuilding the site's registry by either a) using Drush or b) going to
  /admin/modules and clicking Save at the bottom of the page. This will ensure that Drupal is now using the custom
  version's code.</p>
  <p>Note: This practice is discouraged and not supporter because it can:</p>
  <ol>
  <li>Affect site performance,</li>
  <li>Create database continuity issues (different releases/versions of projects may not match up
  with the current DB structure), and</li>
  <li>Future Webspark updates to the module will not take effect on this site.</li>
  </ol>
  ";

    $form['webspark_system'] = array(
      '#weight' => 1001,
      '#type' => 'fieldset',
      '#collapsible' => FALSE,
      '#title' => "Attention Pantheon users:",
    );
    $form['webspark_system']['summary'] = array(
      '#type' => 'markup',
      '#markup' => $summary,
    );
    $form['webspark_system']['explanation'] = array (
      '#type' => 'fieldset',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#title' => t("More information..."),
      '#prefix' => '<div class="explanation-summary">',
      '#suffix' => '</div>',
    );
    $form['webspark_system']['explanation']['summary'] = array(
      '#type' => 'markup',
      '#markup' => $long_message,
    );
  }
}
