<?php
/**
 * @file
 * Code for the Webspark callout feature.
 */

include_once 'webspark_callout.features.inc';

/**
 * Implementation of hook_entity_info_alter().
 */
function websoark_callout_entity_info_alter(&$entity_info) {
  // Webspark callout Widget.
  $entity_info['fieldable_panels_pane']['bundles']['callout'] = array(
    'label' => t('Add ASU callout'),
    'description' => t('Add a 1170 x 380 px callout to the top row'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'webspark_callout') . '/images/icon_callout.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/callout',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function websoark_callout_preprocess_panels_pane(&$variables){
  if(isset($variables['content']['#bundle']) && $variables['content']['#bundle']==='callout' ){
   $variables['title_heading'] = 'h1'; 
  }
}

function websoark_callout_init() {
	drupal_add_js(drupal_get_path('module', 'webspark_callout') . '/js/webspark_callout.js', array('scope' => 'footer', 'group' => JS_THEME, 'weight' => 95));
}
