<?php

/**
 * Helper function - Returns name of temporary table, submissions migrate class name
 * @param string $type
 * @return mixed
 */
function _eoss_webforms_followup_migration_data($type = 'table_nid') {
  $names = array(
    'table_nid' => 'migrate_map_custom_nids',
    'table_cid' => 'migrate_map_custom_cid',
    'class_nid' => 'MigrateWebformSubmissionEOSS',
    'class_cid' => 'MigrateWebformSubmittedDataEOSS',
  );
  return $names[$type];
}
