<?php
/**
 * Implements hook_form_FORM_ID_alter()
 * Adding Check All option - CheckAll module
 */ 
function asu_studyabroad_custom_form_scholarship_node_form_alter(&$form, &$form_state) {
    
  $form['und']['field_ss_destination_country'] = array(
    '#checkall' => TRUE,  
  );  
  $form['und']['field_ss_country_display'] = array(
    '#checkall' => TRUE,  
  );  
  
}

/**
 * Implements hook_form_FORM_ID_alter()
 * Display filter's description
 */ 
function asu_studyabroad_custom_form_views_exposed_form_alter(&$form, &$form_state) {
  $form['field_ss_college_tid']['#description'] = isset($form['#info']['filter-field_ss_college_tid']['description']) ? $form['#info']['filter-field_ss_college_tid']['description'] : '';
  $form['field_ss_diverse_characteristics_tid']['#description'] = isset($form['#info']['filter-field_ss_diverse_characteristics_tid']['description']) ? $form['#info']['filter-field_ss_diverse_characteristics_tid']['description'] : '';  
}

/*
function asu_studyabroad_custom_form_views_ui_edit_display_form_alter(&$form, &$form_state) {
  dpm($form, "form");
  
  $form['options']['views_ef_fieldset']['options']['sort']['container-1']['description']['#size'] = 25;
  
  dpm($form, "form - AFTER");
  
}
*/