<?php
/**
 * Implements hook_form_FORM_ID_alter()
 * Adding Check All option - CheckAll module
 */ 
function asu_studyabroad_custom_form_scholarship_node_form_alter(&$form, &$form_state) {
    
  $form['und']['field_ss_destination_country'] = array(
    '#checkall' => TRUE,  
  );  
  $form['und']['field_ss_country_display'] = array(
    '#checkall' => TRUE,  
  );  
  
}

function asu_studyabroad_custom_form_views_exposed_form_alter(&$form, &$form_state) {
  $form['field_ss_college_tid']['#description'] = '<p>Some text</p>';
  dpm($form, "form");
  
}

