<?php
/**
 * Implements hook_form_FORM_ID_alter()
 * 
 */ 
function asu_studyabroad_custom_form_scholarship_node_form_alter(&$form, &$form_state) {
  
  dpm($form, "form");
  
//  $form['foobar'] = array(
//    '#type' => 'checkboxes',
//    '#options' => $options,
//    '#default_value' => $default_value,
//    '#checkall' => 'unique-class-for-each-checkboxes-column',  // <--- this is it ;-)
//  );  
  
}

